name             'maadbox'
maintainer       'Mark Koh'
maintainer_email 'markkohdev@gmail.com'
license          'All rights reserved'
description      'Installs/Configures maadbox'
long_description 'Installs/Configures maadbox'
version          '0.1.0'

depends 'apt', '~> 2.8.2'
depends 'mysql', '~> 5.5'
depends 'apache2', '~> 3.1.0'
depends 'git', '~> 4.3.4'
depends 'python', '~> 1.4.6'
depends 'ruby', '~> 0.9.3'
depends 'nodejs', '~> 2.4.2'
